name: build-openlane
on: [push]
jobs:
  build-openlane-sky130:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subservient
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@migrate-dockerized
        with:
          libraries: https://github.com/olofk/serv
          core: subservient
          target: sky130
          tool: openlane

